sawari_renewed1/urls.py
from django.conf.urls import patterns, include, url
import mainpage_handler.views
from django.conf import settings


from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
	
	
    url(r'^$', mainpage_handler.views.mainpage_handler),
	url(r'^login/$', mainpage_handler.views.login_handler),
    url(r'^signup/$', mainpage_handler.views.signup), 	
    url(r'^logout/$', mainpage_handler.views.logout_handler),

)

mainpage_handler/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

from datetime import date, timedelta

from geopy import geocoders

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    location = models.CharField(max_length=30)
    rating = models.IntegerField(blank=True, null=True)
    contactno = models.IntegerField(blank=True, null=True)
    vouch_level = models.IntegerField(blank=True, null=True)
    pics = models.FileField(upload_to='E:\INFO\APP-OX\programming\python\projects\sawari_renewed1\sawari_renewed1\media', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
	
    def __unicode__(self):
	    return self.user.first_name

def user_post_save(sender, instance, created, **kwargs):
    """Create a user profile when a new user account is created"""
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(user_post_save, sender=User)

class Vehicle(models.Model):
    vehicle_types = (
        ('SUV', 'SUV'),
        ('SEDAN', 'Sedan'),
        ('MotorBike', 'MotorBIKE'),
        ('Cycle', 'CYCLE'),
        ('Other', 'other'),
        )
    available_vehicle_types = models.CharField(max_length=10, choices=vehicle_types)
    created = models.DateTimeField(auto_now_add=True)
    pics = models.FileField(upload_to='E:\INFO\APP-OX\programming\python\projects\sawari_renewed1\sawari_renewed1\media')
    owner = models.OneToOneField(UserProfile, null=True, blank=True)

class BaseRequest(models.Model):
    sender = models.ForeignKey('UserProfile', related_name='sender')   
    message = models.CharField(max_length=50)
    datetime_from = models.DateTimeField()
    datetime_to = models.DateTimeField()
    status = models.NullBooleanField()
    comments = models.CharField(max_length=100,blank=True, null=True)
    vehicle_type = models.CharField(max_length=120)
    created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.message

class OpenRequest(BaseRequest):
    location = models.CharField(max_length=100)
    sharer = models.ManyToManyField(UserProfile,blank=True, null=True, related_name='openreq_sharer')
    bidder = models.ManyToManyField(UserProfile,blank=True, null=True, related_name='openreq_bidder' )

class PrivateRequest(BaseRequest):
    receiver = models.ForeignKey(UserProfile)


class Reviews(models.Model):
    sender = models.ForeignKey(UserProfile, related_name='reviewer')
    receiver = models.ForeignKey(UserProfile)
    experience_types = ( 
                        ('Positive' , 'positive'),
                        ('Neutral' , 'neutral'),
                        ('Negative' , 'negative')
                        )
    experience = models.CharField(max_length=10, choices=experience_types)
    review = models.CharField(max_length=300)
    created = models.DateTimeField(auto_now_add=True)

class Trips(models.Model):
    trip_id = models.IntegerField(unique=True)
    creator = models.ForeignKey(UserProfile)
    source = models.CharField(max_length=100)
    destination = models.CharField(max_length=100)
    via = models.CharField(max_length=300,null=True,blank=True)
    sharer = models.ManyToManyField(UserProfile,null=True,blank=True, related_name='trip_sharer')
    created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.destination

class Posts(models.Model):
    post = models.CharField(max_length=500)
    creator = models.ForeignKey(UserProfile)
    created = models.DateTimeField(auto_now_add=True)
    location = models.CharField(max_length=200)

    def __unicode__(self):
        return self.post

class Comments(models.Model):
    post = models.ForeignKey(Posts)
    comments = models.CharField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)

class vouch(models.Model):
    voucher = models.ForeignKey(UserProfile)
    vouched = models.ForeignKey(UserProfile, related_name='vouched_user')

mainpage_handler/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User

from mainpage_handler.models import UserProfile, BaseRequest, Trips

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')
    verify_password = forms.CharField(widget=forms.PasswordInput())
    location = forms.CharField()



class RequestForm(forms.Form):
    available_types = (
        ('SUV', 'SUV'),
        ('SEDAN', 'Sedan'),
        ('MotorBike', 'MotorBIKE'),
        ('Cycle', 'CYCLE'),
        ('any', 'any'),
    )
    datetime_to = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'class': 'datetime'}))
    datetime_from = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'class': 'datetime'}))
    type_of_vehicle = forms.ChoiceField(choices=available_types)
    message = forms.CharField()


class LoginForm(forms.Form):
	username = forms.CharField(max_length=30)
	password = forms.CharField(widget=forms.PasswordInput())

class ReviewForm(forms.Form):
    experience_types = ( 
                        ('Positive' , 'positive'),
                        ('Neutral' , 'neutral'),
                        ('Negative' , 'negative')
                        )
    experience = forms.ChoiceField(choices=experience_types)
    review_message = forms.CharField(max_length=300)

class OpenTripForm(forms.Form):
    class Meta:
        model=Trips
        fields=('source','destination','via')
    source = forms.CharField(max_length=200)
    destination = forms.CharField(max_length=200)
    datetime = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'class': 'datetime'}))

mainpage_handler/views.py
from geopy import geocoders
import json

from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from mainpage_handler.models import UserProfile, BaseRequest, OpenRequest, PrivateRequest, Reviews, Trips, Posts

from mainpage_handler.forms import *

from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.cache import cache_page

from mainpage_handler.profile import profile

@csrf_exempt
def mainpage_handler(request):
    msg = ['Welcome to Sawaari' , 'Have an account?', 'New User?']
    query = None
    city=None
    profile_link = None
    lenders = []
    open_request = None
    publicrequests = None
    private_request = None
    review = None
    open_trip = None
    opentrips = None
    context_dir = {}
    post_submit = None
    posts =None
 

    if request.method == 'GET':
        try:
            query = request.GET['query']            
        except:
            pass
        try:
            profile_link = request.GET['profile_link']
        except:
            pass

    if request.method == 'POST':
        try:
            open_request = request.POST['open_request']
        except:
            pass
        try:
            private_request = request.POST['private_request']
        except:
            pass
        try:
            review = request.POST['review']
        except:
            pass
        try:
            open_trip = request.POST['open_trip']
        except:
            pass
        try:
            post_submit = request.POST['post_submit']
        except:
            pass

    if post_submit:
        forum_post = request.POST['forum_post']
        if not query:
            post_location = request.user.userprofile.location
        else:
            post_location = query
        new_post = Posts.objects.create(creator=request.user.userprofile, post = forum_post, location = post_location )
        

    lt, lng = 20.295549, 85.807471
    if query:
        city = ''
        for letter in str(query):
            if letter == ',':
                break
            city = city + str(letter)
            city = str(city)
            # return HttpResponse(query)

        try:
            gmap = geocoders.GoogleV3()
            place, (lt, lng) = gmap.geocode(query)
            # return HttpResponse(lt)
        except:
            # return HttpResponse(lt)
            lt, lng = 20.295549, 85.807471

        lenders = UserProfile.objects.filter(location__icontains=query)
        publicrequests = OpenRequest.objects.filter(location__icontains=query)
        opentrips = Trips.objects.filter(source__icontains=query)
        posts = Posts.objects.filter(location__icontains=query)

    openrequest_location = query

    loggedin = request.user.is_authenticated()
    user = None
    if loggedin:
        user = request.user
        if not query:
            posts = Posts.objects.filter(location__icontains=request.user.userprofile.location)
            posts = posts.order_by('created')

    if open_request:
        openrequest_location = request.GET['query']
        datetime_from = request.POST["datetime_from"]
        datetime_to = request.POST["datetime_to"]
        message = request.POST["message"]
        type_of_vehicle = request.POST["type_of_vehicle"]
        openrequest = OpenRequest.objects.create(sender=request.user.userprofile, datetime_from=datetime_from,
                    datetime_to=datetime_to, message=message, location = openrequest_location)
        context_openrequest =  {'open_request' : open_request}
        context_dir.update(context_openrequest)   
        messages.info(request, 'Your open-request has been created')

    profiles = UserProfile.objects.all()
    usernames = [profile.user.username for profile in profiles if profile.location]
    locations = [profile.location for profile in profiles if profile.location]
    latitudes = []
    longitudes = []
    try:
        gmap = geocoders.GoogleV3()
        for location in locations:
            try:
                lat = gmap.geocode(location)[1][0]
                lang = gmap.geocode(location)[1][1]
                longitudes.append(lang)
                latitudes.append(lat)
            except:
                pass
    except:
        pass

    opentrip_form = OpenTripForm()
        
    context_main = {'head_title': 'Welcome to Sawaari',
                   'page_title': 'Welcome to Sawaari',
                   'loggedin': loggedin,
                   'user': user,
                   'welcome_message' : msg[0],
                   'login_prompt' : msg[1],
                   'signup_prompt' : msg[2] ,
                   'query' : query ,
                   'city' : city ,
                   'lenders' : lenders ,
                   'publicrequests' : publicrequests,
                   'opentrips' :opentrips,
                   'profile_link' : profile_link ,
                   'posts' :posts ,
                   'lt' : lt,
                   'lng': lng,
                   'latitudes': json.dumps(latitudes),
                   'longitudes': json.dumps(longitudes),
                   'usernames': json.dumps(usernames),
                   'opentrip_form' : opentrip_form,
                   }
    context_dir.update(context_main)

    if loggedin:
        user = request.user
        profile = user.userprofile
        context_dir.update({'openrequests' : OpenRequest.objects.filter(location__icontains=profile.location), 'profile':profile})
        if query:
            request_form = RequestForm()
            context_dir.update({'request_form' : request_form})

    if profile_link:
        try:
            prof = User.objects.get(username=str(profile_link))
        except:
            raise Http404('Requested user not found.')
        try:
            profile = prof.get_profile()
        except:
            raise Http404("Requested page couldn't be retrieved.")
        if profile:
            request_form = RequestForm()
            review_form = ReviewForm()
            loggedin = request.user.is_authenticated()
            not_my_profile = False
            if (request.user != profile.user):
                not_my_profile = True

            try:
                gmap = geocoders.GoogleV3()
                place, (lt, lng) = gmap.geocode(profile.location)
            except:
                pass

            reviews = Reviews.objects.filter(receiver=(User.objects.get(username=request.GET['profile_link']).get_profile()))

            sent_requests = PrivateRequest.objects.filter(sender=profile)
            received_requests = PrivateRequest.objects.filter(receiver=profile)
            visitors_requests = None
            if loggedin:
                visitors_requests = PrivateRequest.objects.filter(sender=request.user.get_profile(), receiver=profile)

            context_profile = {'profile': profile, 'request_form': request_form,
                                'not_my_profile': not_my_profile, 'sent_requests': sent_requests,
                                'received_requests': received_requests, 'visitors_requests': visitors_requests,'lt':lt,
                                'lng':lng ,'profile_location':profile.location, 'review_form': review_form, 'reviews' : reviews}
            context_dir.update(context_profile)

    if review:
        new_review = Reviews.objects.create(sender=request.user.userprofile, receiver=(User.objects.get(username=request.GET['profile_link']).get_profile()),
            experience=request.POST['experience'], review=request.POST['review_message'])
        messages.info(request, 'Your Review Has Been Posted')


    if private_request:
        
        type_of_vehicle = request.POST["type_of_vehicle"]
        datetime_to = request.POST["datetime_to"]
        datetime_from = request.POST["datetime_from"]  
        message = request.POST["message"]
        private_request = PrivateRequest.objects.create(sender=request.user.userprofile,
                                                        receiver=(User.objects.get(username=request.GET['profile_link']).get_profile()),
                                                        datetime_from=datetime_from,
                                                        datetime_to=datetime_to, message=message)
        messages.info(request, 'Your request has been created')


    if open_trip:
        source = request.POST['source']
        destination = request.POST['destination']
        new_trip = Trips.objects.create(creator=request.user.userprofile, source=source,destination=destination)
        messages.info = (request, 'Your trip has been created')        


    return render_to_response('mainpage_handler.html', context_dir, context_instance=RequestContext(request))
    

@csrf_exempt
def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        location = request.POST['location']
        try:
            gmap = geocoders.GoogleV3()
            place, (lt, lng) = gmap.geocode(location)
        except:
            pass
        password = request.POST['password']
        verify_password = request.POST['verify_password']
        if password == verify_password:
            user = User.objects.create_user(username=username, email=email, password=password)
            user.first_name = first_name
            user.last_name = last_name
            user.save()
            custom_user = user.get_profile()
            custom_user.location = location
            custom_user.save()
            user = authenticate(username=username, password=password)
            login(request, user)

sawari_renewed1/templates/autocomplete.html
   
<html>
<head>
	<title> autocomplete </title>
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/autocomplete.css">
</head>
<body>
   <form class="navbar-form span6" action="/lender_search/" method="get">
  	     <input  autocomplete="off" id="place-search" name="query" placeholder="Where would you like to go?" type="text">
  	     <button type="submit">Search</button>
  </form>

    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script> </script>
	<script type="text/javascript">
       	var input = document.getElementById('place-search');
        var autocomplete = new google.maps.places.Autocomplete(input);
	</script>
</body>
</html>

sawari_renewed1/templates/datepick.html
<!doctype html>
 
<html>
<head>
  <title>jQuery UI Datepicker</title>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css" />
  <script src="http://code.jquery.com/jquery-1.8.3.js"></script>
  <script src="http://code.jquery.com/ui/1.10.0/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css" />
  <script>
  $(function() {
    $( "#datepicker" ).datepicker();
  });
  </script>
</head>
<body>
 
<p>Date: <input type="text" id="datepicker" /></p>
 
 
</body>
</html>

sawari_renewed1/templates/feeds.html
{%if openrequests%}
    <h3>People looking for vehicles at {{profile.location}}:</h2>
    <ul>
        {% for request in openrequests%}
            <li><p><strong>
            <a class="btn btn-large btn-info" href="/?profile_link={{request.sender}}"> {{request.sender}} </a>
            </strong></p>
            <p>{{request.message}}</p></li>
        {%endfor%}
    </ul>
{%else%}
    <h3>Currently No one looking for vehicles at {{profile.location}}</h3>
{%endif%}

sawari_renewed1/templates/forum.html
{%if loggedin %}
    {%if not profile_link %}

        <div style="z-index:2; background-color: black; opacity: 0.6; color: white; padding :20px; border-radius : 10% / 10%;
			 position: absolute; margin-top:7%; margin-left: 70%;width : 25%;">

            <form action="." method="post">
                <ui style="list-style-type:None;">
                <li>
                    <input type="text" name="forum_post" class="span3">
                    <button type="submit" class="badge badge-important" name="post_submit" value="submit">Post</button>
                </li>
                </ui>
            </form>
            {%if not query%}
            <h5>Current Posts tagged at {{profile.location}}:</h5>
            {%else%}
            <h5>Current Posts tagged at {{query}}:</h5>
            {%endif%}

            <ul style="list-style-type:decimal;">
                {% for post in posts%}
                    <li>
                        <p>{{post.post}}  &nbsp; &nbsp; &nbsp; &nbsp; {{post.created}}</p>
                        <p><strong>
                        <a href="/?profile_link={{request.sender}}"> {{post.creator}} </a>
                        </strong></p>
                    </li>
                {%endfor%}
            </ul>

        </div>

    {%endif%}
{%else%}

    {%if not profile_link%}
        {%if query%}
            <div style="z-index:2; background-color: black; opacity: 0.6; color: white; padding :20px; 
                border-radius : 10% / 10%; position: absolute; margin-top:7%; margin-left: 77%;">
                <h5>login to see this city's forum</h5>
            </div>
        {%endif%}
    {%endif%}
{%endif%}

sawari_renewed1/templates/lender_profile.html
{% extends "base.html" %}
{% block title %}{{ profile.user.username }}'s profile{% endblock %}
{% block custom_stylesheets %}
	<link rel="stylesheet" href="http://localhost:8000/media/lender_profile.css"/>
	 <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css" />
	 <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/timepicker.css">
  {% endblock %}
{% block content %}
	{% include "includes/signup.html" %}
	{% include "includes/login.html" %}
	{% include "includes/request_form.html" %}
	<div class="span2"></div>
	<div class="span8">
		<div class="row" style="padding-top:50px;">
			<div class="span3">
				<img src="http://placehold.it/80x80" class="img-polaroid" style="margin:20px;">
				{% if not request_to_lender %}
					{%if not_my_profile %}
						<form action="" method="GET">
							<a data-toggle="modal" data-target={%if loggedin%}
							"#request-form-modal"{% else %}"#login-modal"{% endif %} 
							class="btn btn-large btn-primary" style="width:50%" href="#">Request</a>
						<form>
					{%endif%}
				{%endif%}
			</div>
			<div class="span5">
				<table class="table table-hover">
					<tr class="success">
						<td>Name : {{profile.user.first_name}} {{profile.user.last_name}}</td>
					</tr>
					<tr class="error">
						<td>Location : <a href="/lender_search/?query={{profile.location}}">{{profile.location}}</a></td>
					</tr>
					<tr class="warning">
						<td>Email : {{profile.user.email}}</td>
					</tr>
					<tr class="info">
						<td>Contact Number : {{profile.contactno}}</td>
					</tr>
					<tr class="success">
						<td>Vehicle's Available : {{profile.available_vehicle_types}}</td>
					</tr>
				</table>
			</div>
		</div>	
		<div class="row">
			{%if not_my_profile %}
				<div class="span8">
					<h3>Request's sent to {{profile.user.username}}</h3>
					{% if visitors_requests %}
					<table class="table table-hover">
						<tr>
							<th>From</th>
							<th>To</th>
							<th>Message</th>
							<th>Status</th>
						</tr>
						{% for request in visitors_requests %}
							<tr>
								<td>{{request.datetime_from}}</td> 
								<td>{{request.datetime_to}}</td>
								<td>{{request.message}}</td>  
								<td>{{request.status}}</td>
							</tr>
						{% endfor %}
					</table>
					{% else %}
					<h5>No requests sent.</h5>
					{% endif %}
			{% else %}
				<div class="span4">
					<h5>Sent Requests</h5>
					{% if sent_requests %}
					<table class="table table-hover">
						<tr>
							<th>Receiver</th>
							<th>From</th>
							<th>To</th>
							<th>Message</th>
							<th>Status</th>
						</tr>
						{% for request in sent_requests %}
							<tr>
								<td><a href="/profile/{{request.receiver}}/"> {{request.receiver}} </a> </td>
								<td>{{request.datetime_from}}</td> 
								<td>{{request.datetime_to}}</td>
								<td>{{request.message}}</td>  
								<td>{{request.status}}</td>
							</tr>
						{% endfor %}
					</table>
					{% else %}
						<p>No requests sent.</p>
					{% endif %}
				</div>
				<div class="span4">
					<h5>Received Requests</h5>
					{% if received_requests %}
					<table class="table table-hover">
						<tr>
							<th>From</th>
							<th>To</th>
							<th>Message</th>
							<th>Status</th>
						</tr>
						{% for request in received_requests %}
							<tr>
								<td>{{request.datetime_from}}</td> 
								<td>{{request.datetime_to}}</td>
								<td>{{request.message}}</td>  
								<td>{{request.status}}</td>
							</tr>
						{% endfor %}
					</table>
					{% else %}
					<p>No requests received</p>
					{% endif %}
				</div>
			{% endif %}
		</div>	
	</div>
	<div class="span2"></div>
{% endblock %}
{% block body_js %}
    <script src="http://code.jquery.com/ui/1.10.0/jquery-ui.js"></script>
    <script src="{{ STATIC_URL }}js/jquery.totemticker.js"></script>
    <script src="{{ STATIC_URL }}js/jquery-ui-timepicker-addon.js"></script>
	<script>
	  $(function() {
	    $("#id_datetime_from").datetimepicker({
			timeFormat: "HH:mm",
			dateFormat: "yy-mm-dd"
		});
	    $("#id_datetime_to").datetimepicker({
			timeFormat: "HH:mm",
			dateFormat: "yy-mm-dd"
		});
	  });
  	</script>
{% endblock %}

sawari_renewed1/templates/lender_search.html
{% extends "base.html" %}
{% block title %}Lender Search Results{% endblock %}

{% block custom_stylesheets %}
<link rel="stylesheet" href="http://localhost:8000/media/lender_search.css" />

{% endblock %}

{% block content %}

<div class="span2"></div>
	<div class="lender_list">
	{%if lenders%}
	<p> <strong> Found following lenders {{lender|pluralize}} at {{ query }} : </strong> </p>
		<ul>
			{% for profile in lenders %}
			<li>
				<p> <a href="/profile/{{profile.user.username}}"> {{ profile.user.first_name }} {{profile.user.last_name}}</a></p>
				<p> {{profile.available_vehicle_types}} </p>
			</li>
			{% endfor %}
		</ul>
	</div>
	
	<iframe class = "map" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" width="1000" height="300"
	        src="http://maps.google.com/?ie=UTF8&amp;ll={{latitude}},{{longitude}}&amp;spn=0.040623,0.077162&amp;z=8&amp;output=embed" alt="couldn't load the map..">
	</iframe>
	
	{% else %}
	<div class="no_results">
		<p>Currently <strong>NO</strong> lenders available at <strong>{{ query }}</strong> .</p>
	</div>
	{% endif %}
 
	<form class="back_button">
		<INPUT Type="button" VALUE="<---" onClick="history.go(-1);return true;">
	</form>
{% endblock %}

sawari_renewed1/templates/login.html
<html>
<head>
    <title>Login</title>
</head>
<body>
   	<p>{% if errors %}
        <ul>
            {% for e in errors %}
            <li>{{ e }}</li>
            {% endfor %}
        </ul>
    {% endif %}</p>
	
	<form action="/login/" method="POST">
		{% csrf_token %}
		
		{{form.as_p}}
		
		<input type="submit" value="Submit" />

	</form>

</body>
</html>

sawari_renewed1/templates/nav.html
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
	  <div class="container" style="width: 100%; background-color: black;">
		  <a class="brand" style="color: white; background-color: green; padding-left: 30px;" href="/">  Sawaari </a>
      	  	
  		  <ul class="nav pull-right" style="margin:auto;">

  	         <li>

  	         	<form class="navbar-form span4" action="" method="get">
  	         	  <input  autocomplete="off" id="place-search" name="query" placeholder="Where would you like to go?" tabindex="1" type="text" class="span3 search-query">
  	         	  <button type="submit" class="btn btn-primary">Search</button>
  	         	</form>

              <form class="navbar-form span0" action="" method="post">
                <a data-toggle="modal" data-target={%if loggedin%}"#open-trip-modal"{% else %}"#login-modal"{%endif%} style="color:white" href="#">
                  <button type="submit" name="open_trip" class="btn btn-info">Plan An Open Trip
                  </button>
                </a>
              </form>

              <div class ="span1"></div>


  	         </li>
           
            {%if loggedin%}

                {%if query%}
                  <li>
                      <form class="navbar-form span4" action="" method="get">
                      <a data-toggle="modal" data-target={%if loggedin%}"#open-request-modal"{% else %}"#login-modal"{%endif%} style="color:white" href="#">     
                        <button type="submit" name="open_request" class="btn btn-danger">Post An Open Request at {{city}}
                           </button></a>
                      </form>
                  </li>
                {%endif%}
                
              <li><a class="pull-right" style="color:white" href="/?profile_link={{user.username}}">My Profile</a></li>
              <li><a class="pull-right" style="color:white" href="/logout">Logout</a></li>

            {% else %}

              {%if query%}
                  <li>
                      <form class="navbar-form span4" action="" method="get">
                      <a data-toggle="modal" data-target={%if loggedin%}"#open-request-modal"{% else %}"#login-modal"{%endif%} style="color:white" href="#">     
                        <button type="submit" name="open_request" class="btn btn-danger">Post An Open Request at {{city}}
                           </button></a>
                      </form>
                  </li>
                {%endif%}

              <li><a data-toggle="modal" data-target="#login-modal" class="pull-right" style="color:white" href="#">Login</a></li>

            {%endif%}
  		  </ul>
	  </div>
 
  </div>
</div>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script> </script>
    <script type="text/javascript">
        var input = document.getElementById('place-search');
        var autocomplete = new google.maps.places.Autocomplete(input);
    </script>

sawari_renewed1/templates/renter_page.html
<html>
<head>
    <title>Search</title>
	<link rel="stylesheet" href="http://localhost:8000/media/renter_page.css" />
</head>
<body>
	<img class='background' src="http://localhost:8000/media/Aston_Martin.gif" alt= "unable to load image.."/>
	<div class= "renter_form">
		<form action="/lender_search/" method="get">

		    <label for "location"> <p> <strong> Enter Location : </strong> </P> </label>
			<input id="location" type="text" name="query"><br>
			
				<div class="filters">
					<input id="motorbike" type="checkbox" name="vehicle" value="MotorBike">
					<label for="motorbike">motorbike</label> <br>
					<input id="suv" type="checkbox" name="vehicle" value="SUV">
					<label for="suv">SUV</label> <br>
					<input id="sedan" type="checkbox" name="vehicle" value="SEDAN">
					<label for="sedan">SEDAN</label> <br>
					<input id="cycle" type="checkbox" name="vehicle" value="Cycle">
					<label for="cycle">Cycle</label> <br>
					<input id="others" type="checkbox" name="vehicle" value="Others">
					<label for="others">Others</label> <br>
					<input class="search_button" type="submit" value="Search">
				</div>
				
		</form>
	</div>
</body>
</html>